### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by soloano** [hExPY/blsspainvisa-auto-filler#1]
hello, 
I want to use this blsspainvisa-auto-filler.user.js  for regroupment familial  is this work or no

**Comment by awin-marvynzalewski** [comment]
Hey @soloano of course it works! What's your problem mate?

**Comment by hExPY** [comment]
Hi @soloano 
Of course it works! What's the problem buddy? Did you read the README?

**Comment by soloano** [comment]
please what I need to change in script I'm in morocco

**Comment by hExPY** [comment]
Hi @soloano 

Did you manage to get it running? Its all written in the file.

**Comment by codebytaha** [comment]
Hello @hExPY 
First of all thanks for this script,
Brother can you please create script for 3-4 family members.
It will really mean alot :)

**Comment by hExPY** [comment]
Hi @codebytaha 
I was checking to do that but apparently the website changed and now requires you an account. I don't have an account and currently not in the need of creating one.
Looks like you're a fellow engineer yourself, am looking forward to a pull request from you improving the script!

Best regards,
Marvyn :)
