### ISSUE TITLE
field values for e.g. VisaTypeId 

### ISSUE THREAD

**Issue by Anfisaaaaaa** [hExPY/blsspainvisa-auto-filler#2]
How can I find out the field values for e.g. VisaTypeId ?

**Comment by awin-marvynzalewski** [comment]
Hi @Anfisaaaaaa it used to be in the HTML code as ID of the field. However, I don't think it works anymore due to the fundamental changes of the website.

**Comment by hExPY** [comment]
Hi @Anfisaaaaaa it used to be in the HTML code as ID of the field. However, I don't think it works anymore due to the fundamental changes of the website.
